name: CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.17' ]
    name: CI with go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test
